package refmsg

const (
	NOTIFY_ADD_FRIEND              = 101
	NOTIFY_ADD_FRIEND_TITLE        = "添加好友"
	NOTIFY_ADD_FRIEND_ACCEPT       = 102
	NOTIFY_ADD_FRIEND_ACCEPT_TITLE = "添加好友"
	NOTIFY_INVITE_JOIN_GROUP       = 103
	NOTIFY_INVITE_JOIN_GROUP_TITLE = "入群邀请"

	NOTIFY_JOIN_GROUP       = 104
	NOTIFY_JOIN_GROUP_TITLE = "加入群"

	NOTIFY_CIRCLE_PRIZE         = 201
	NOTIFY_CIRCLE_PRIZE_TITLE   = "朋友圈点赞"
	NOTIFY_CIRCLE_COMMENT       = 202
	NOTIFY_CIRCLE_COMMENT_TITLE = "朋友圈评论"
	NOTIFY_CIRCLE_REPLY         = 203
	NOTIFY_CIRCLE_REPLY_TITLE   = "朋友圈评论"
)
